name: Handle deployments 
on:
  push:
    branches:
      - main
    paths:
      - migration/deployments.py
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: prefecthq/prefect:latest
    env: 
      KEY: ${{ secrets.PREFECT_TENANT_API_KEY}}
    steps:
    - uses: actions/checkout@v2
    - uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt
    - name: Authenticate to Prefect dependencies
      run: prefect auth login -k $KEY
    - name: Run deployment
      run: prefect deployment create deployments.py